#******************************************************************************************************************
# File: docker-compose-base.yaml
# Project: MSIT-SE Studio Project (Data61)
# Copyright: Team Unchained
# Versions:
#   1.0 March 2018 - Modified based on a sample file (Dongliang Zhou)
#   2.0 May 2018 - Transformed into a template for autogeneration (Dongliang Zhou)
#
# Description: This is the template base file defining peer docker containers to simulate testing network.
#
# External Dependencies: Hyperledger fabric library
#
#*****************************************************************************************************************/

# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:\$IMAGE_TAG
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=\${COMPOSE_PROJECT_NAME}_${unique_id}
      - CORE_LOGGING_LEVEL=INFO
      # - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
