    - &${peerName}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ${peerName}MSP

        # ID to load the MSP definition as
        ID: ${peerName}MSP

        MSPDir: crypto-config/peerOrganizations/${peerDomainPrefix}.${domain}/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.${peerDomainPrefix}.${domain}
              Port: 7051