  couchdb.peer${peerNumber}.${peerDomainPrefix}.${domain}:
    container_name: couchdb.peer${peerNumber}.${peerDomainPrefix}.${domain}
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 222${portIdx}:5984
    networks:
      - ${uniqueId}