NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Lane1.Z2refeI.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Lane1.Z2refeI.com-cert.pem
    OrganizationalUnitIdentifier: peer
