#******************************************************************************************************************
# File: docker-compose-cli.yaml
# Project: MSIT-SE Studio Project (Data61)
# Copyright: Team Unchained
# Versions:
#   1.0 March 2018 - Modified based on the template (Dongliang Zhou)
#   2.0 May 2018 - Transformed into a template for autogeneration (Dongliang Zhou)
#
# Description: This is the template file defining docker containers to simulate testing network.
#
# External Dependencies: Hyperledger fabric library
#                        base\docker-compose-base.yaml
#                        base\peer-base.yaml
#
#*****************************************************************************************************************/

# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.Z2refeI.com:
  peer0.Lane1.Z2refeI.com:
  couchdb.peer0.Lane1.Z2refeI.com:
  peer1.Lane1.Z2refeI.com:
  couchdb.peer1.Lane1.Z2refeI.com:
  peer2.Lane1.Z2refeI.com:
  couchdb.peer2.Lane1.Z2refeI.com:
  peer3.Lane1.Z2refeI.com:
  couchdb.peer3.Lane1.Z2refeI.com:


networks:
  Z2refeI:

services:

  orderer.Z2refeI.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.Z2refeI.com
    container_name: orderer.Z2refeI.com
    networks:
      - Z2refeI

  couchdb.peer0.Lane1.Z2refeI.com:
    container_name: couchdb.peer0.Lane1.Z2refeI.com
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 2221:5984
    networks:
      - Z2refeI
  couchdb.peer1.Lane1.Z2refeI.com:
    container_name: couchdb.peer1.Lane1.Z2refeI.com
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 2222:5984
    networks:
      - Z2refeI
  couchdb.peer2.Lane1.Z2refeI.com:
    container_name: couchdb.peer2.Lane1.Z2refeI.com
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 2223:5984
    networks:
      - Z2refeI
  couchdb.peer3.Lane1.Z2refeI.com:
    container_name: couchdb.peer3.Lane1.Z2refeI.com
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 2224:5984
    networks:
      - Z2refeI

  # docker-compose-cli-peer.yaml content goes here
  # docker-compose-cli-cli.yaml content goes here
  peer0.Lane1.Z2refeI.com:
    container_name: peer0.Lane1.Z2refeI.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Lane1.Z2refeI.com
    networks:
      - Z2refeI
    depends_on: 
     - couchdb.peer0.Lane1.Z2refeI.com
  peer1.Lane1.Z2refeI.com:
    container_name: peer1.Lane1.Z2refeI.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Lane1.Z2refeI.com
    networks:
      - Z2refeI
    depends_on: 
     - couchdb.peer1.Lane1.Z2refeI.com
  peer2.Lane1.Z2refeI.com:
    container_name: peer2.Lane1.Z2refeI.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.Lane1.Z2refeI.com
    networks:
      - Z2refeI
    depends_on: 
     - couchdb.peer2.Lane1.Z2refeI.com
  peer3.Lane1.Z2refeI.com:
    container_name: peer3.Lane1.Z2refeI.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.Lane1.Z2refeI.com
    networks:
      - Z2refeI
    depends_on: 
     - couchdb.peer3.Lane1.Z2refeI.com
  Lane1_Z2refeI_cli:
    container_name: Lane1_Z2refeI_cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GODEBUG=netdns=go
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=Lane1_cli
      - CORE_PEER_ADDRESS=peer0.Lane1.Z2refeI.com:7051
      - CORE_PEER_LOCALMSPID=Lane1MSP
      - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Lane1.Z2refeI.com/peers/peer0.Lane1.Z2refeI.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Lane1.Z2refeI.com/peers/peer0.Lane1.Z2refeI.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Lane1.Z2refeI.com/peers/peer0.Lane1.Z2refeI.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Lane1.Z2refeI.com/users/Admin@Lane1.Z2refeI.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.Z2refeI.com
# docker-compose-cli-depends-on.yaml content goes here
      - peer0.Lane1.Z2refeI.com
      - peer1.Lane1.Z2refeI.com
      - peer2.Lane1.Z2refeI.com
      - peer3.Lane1.Z2refeI.com

    networks:
      - Z2refeI

